### ISSUE TITLE
使用ShareLaTeX部署开源版本的overleaf

### ISSUE THREAD

**Issue by Huangxt57** [SYSU-SCC/sysu-thesis#15]
针对模版在overleaf上编译过慢的问题，主要原因有两点：
- 网络问题导致编译好的pdf文件在网页上渲染过慢
- overleaf本身的编译服务器太弱，导致编译过慢

针对上述两点，可以使用[这个仓库](https://github.com/overleaf/overleaf)的overleaf开源版本。

具体部署可以参考[这个页面](https://www.notion.so/melonhwang/Overleaf-fad41772ce6f43a19c5766b161147f33)，晚上在2C 4G的阿里云服务器上试了下，速度还是比overleaf快很多的。

考虑之后是否能向学院/学校申请服务器资源，直接在校园网内搭建编译服务器，既省去了本地配置环境的麻烦，也不用忍受捉急的网络过慢的问题。

**Comment by wwyf** [comment]
这个我部署过，确实体验不错

**Comment by wwyf** [comment]
我自己做了一个overleaf镜像，内含texlive2021，包含足够的字体，可用于自行搭建可编译毕设模板的overleaf：
[链接](https://hub.docker.com/layers/145883046/wwyf/overleaf/2.5.2-full/images/sha256-38f63de20dbe4c5cda1d33d3e289d6efce805f3eae7fefc2f78bf7d34f9080c3?context=explore)
