### ISSUE TITLE
封面-题目如何删除第二行的下划线？

### ISSUE THREAD

**Issue by Passionzq** [SYSU-SCC/sysu-thesis#22]
您好，我的题目第一行内可以写完，请问应该如何删除第二行的下划线？

**Comment by wwyf** [comment]
可以修改 `sysuthesis.cls` 文件，可见如下（大约269~270行附近）
![image](https://user-images.githubusercontent.com/23121291/114705797-b7ba7600-9d5a-11eb-92a0-dc43553c000b.png)

效果是：
![image](https://user-images.githubusercontent.com/23121291/114705828-c30da180-9d5a-11eb-8b4b-2801337277ed.png)

**Comment by wwyf** [comment]
另外我觉得，其实可以不用去掉，一方面是没有影响，另一方面模板封面本身就是固定的
