### ISSUE TITLE
文档里面普朗克常数\hbar显示不正常。

### ISSUE THREAD

**Issue by BadeSummer** [SYSU-SCC/sysu-thesis#26]
### 主要问题：pdf中数学环境里面\hbar显示不正常。
![image](https://user-images.githubusercontent.com/39992551/115180891-420f2b00-a109-11eb-8385-7e8e01733772.png)  

### 尝试解决方法：
1. 在cls模版里`\RequirePackage{fontspec}`语句加上`[no-math]`参数，即修改成`\RequirePackage[no-math]{fontspec}`。结果导致编译时出现`\setmainfont{Times New Roman} undefine`报错。
2. 尝试自己重新定义\hbar命令，在main.tex文档开始前加入`\renewcommand{\hbar}{\mathchar'26\mkern-9mu h}`。结果：普朗克符号没有发生变化，似乎是定义没有被“读取”？在我个人的例子中，我还有其他定义`\newcommand{\mean}[1]{\langle #1 \rangle}`都是可以正常工作的。只是\hbar这一条定义无法产生效果。

**Comment by BadeSummer** [comment]
已经解决：`no-math`参数只能在调用模版的时候用。所以需要`\documentclass[no-math]{sysuthesis}`。

**Comment by wwyf** [comment]
赞👍，有解决方案就很棒
