### ISSUE TITLE
「keywords」 or「 key words」? 

### ISSUE THREAD

**Issue by DanielXuuuuu** [SYSU-SCC/sysu-thesis#27]
知网 writeaid 论文写作助手 写作检测后显示如下问题：

![image](https://user-images.githubusercontent.com/43327285/115489293-8841c700-a28e-11eb-8997-b3cf81fe949a.png)

**Comment by wwyf** [comment]
目前模板中使用的是：Keywords，参考该行 https://github.com/SYSU-SCC/sysu-thesis/blob/master/sysuthesis.cls#L872
```
    % F6 英文摘要内容，小四号
    % F7 英文关键词，小四号，加粗
    \zihao{-4}
    \@eabstract
    \paragraph{\textbf{[Keywords]}}\@ekeywords
}
```

我自己认为使用Keywords更为合适，一些论文本身就是用keywords，如[ACM的论文模板](https://www.acm.org/publications/proceedings-template)，具体用哪个更好，我认为大家统一即可。
如由于该问题导致一些学院组织的审核出现问题，也希望能够提醒提醒~
