### ISSUE TITLE
更换字库后，无法使用\bfseries进行加粗

### ISSUE THREAD

**Issue by SummerStar666** [SYSU-SCC/sysu-thesis#28]
![屏幕截图](https://user-images.githubusercontent.com/50078285/115702123-1dca7d00-a39b-11eb-8ea1-91308009407b.png)
由于默认使用的字库中无法显示生僻字，更换使用Windows的字库。更换后，无法使用\bfseries给目录章节标题进行加粗。请问该如何解决呢？

**Comment by sikouhjw** [comment]
「中易宋体」没有对应的粗体，因此映射到了「中易黑体」，如果要「伪粗体」，需要设置 `AutoFakeBold=true`

**Comment by SummerStar666** [comment]
问题解决了，谢谢！
