### ISSUE TITLE
近期TODO list

### ISSUE THREAD

**Issue by wwyf** [SYSU-SCC/sysu-thesis#34]
#30 
#29 
#23
以及相关问题：
1. 写作规范没有要求页眉
2. 二级及以下标题是宋体小四加粗左对齐空两格，二级标题没有左对齐空两格
3. 标题模板有「、」，但是写作规范要求不能有标点符号

因为近期实在没空，大约将会在5月14号以及之后陆续fix掉

**Comment by huangjj27** [comment]
> 大约将会在5月14号以及之后陆续fix掉 

这个是时间点已经过了某些学院的 deadline 了…

**Comment by wwyf** [comment]
> > 大约将会在5月14号以及之后陆续fix掉
> 
> 这个是时间点已经过了某些学院的 deadline 了…

前几天刚好是比赛最关键的那几天，大家都没什么空来修，现在来fix了

**Comment by wwyf** [comment]
重新反思了一下，关于二级标题的定义，应当与我目前的模板设置一致，这点应该是不用改的。

![image](https://user-images.githubusercontent.com/23121291/118396209-083a3180-b681-11eb-9de0-60a3978046b6.png)

**Comment by wwyf** [comment]
关于页眉，考虑到现在有同学反映有老师因为本模板而默认需要页眉，暂时不做改动。
不过这里提供去掉页眉的方法：
![image](https://user-images.githubusercontent.com/23121291/118396490-5ef43b00-b682-11eb-8409-14fcfec5cd45.png)
