### ISSUE TITLE
封面处指导老师不用加职称，而扉页需要职称

### ISSUE THREAD

**Issue by zhangblong** [SYSU-SCC/sysu-thesis#37]
有同学反映说（可能是个例？）封面处指导老师不用加职称，而扉页需要职称，而在info.tex中找不到可以处理这种差异的命令，建议在sysuthesis.cls里多定义一个类似cmentor的命令以处理这个差异。

**Comment by wwyf** [comment]
翻了一下，应该是需要职称的？
![image](https://user-images.githubusercontent.com/23121291/118354007-8f14de80-b59b-11eb-8ef4-11d13a99a333.png)

**Comment by zhangblong** [comment]
> 翻了一下，应该是需要职称的？
> ![image](https://user-images.githubusercontent.com/23121291/118354007-8f14de80-b59b-11eb-8ef4-11d13a99a333.png)

我也看到了，那应该是个例了，感谢回答！
