### ISSUE TITLE
online 文献怎样让 url 和正文同一行？

### ISSUE THREAD

**Issue by Jason5Lee** [SYSU-SCC/sysu-thesis#38]
答辩时老师提的要求，目前如下代码

```
@online{kubefed,
      title        = {Kubernetes Cluster Federation},
      url = {https://github.com/kubernetes-sigs/kubefed},
      urldate = {2021-04-11},
      year         = 2021,
    }
```

渲染效果为

![image](https://user-images.githubusercontent.com/25118271/118785499-7d954480-b8c3-11eb-9bf3-8fd81c8a6e14.png)

URL 位于文本下一行。
现在我想调整使得 URL 和文本同一行，网上查了很多配置都不行，有没有 LaTeX 大佬能指导下？

**Comment by sikouhjw** [comment]
用 texlive 2021 没有这个问题
