### ISSUE TITLE
\hbar的渲染问题

### ISSUE THREAD

**Issue by wangfh5** [SYSU-SCC/sysu-thesis#40]
在正文中输入公式符号$\hbar$，发现编译之后符号异常，bar的位置过于靠上，这通常在amsmath宏包中并不会出现
```
$E=\hbar \omega$
```
![image](https://user-images.githubusercontent.com/51868839/155832578-72dd1cc6-f691-40ca-9c65-96d3f92e150b.png)

怀疑是模板中的某个地方（引用的某个宏包）将命令$\hbar$重新定义了。暂时的解决方式是在`main.tex`中正文开始处增加一行代码重新定义`\hbar` 
```
...
\begin{document}
\renewcommand{\hbar}{h\hspace*{-0.35em}\bar{}\hspace*{0.35em}}
......
```
编译结果为： 
![image](https://user-images.githubusercontent.com/51868839/155832570-7052a347-6a4e-46a5-a5b7-69501cb70381.png)

注意这行重定义命令经过尝试，只能在正文区加入才能生效，如果像下面这样塞入导言区则不会生效，原因可能是导言区中的某个宏包将`\hbar`给又重新定义了
```
...
\renewcommand{\hbar}{h\hspace*{-0.35em}\bar{}\hspace*{0.35em}}
\begin{document}
...
```

**Comment by wu-kan** [comment]
收到，我们看一下怎么调整

**Comment by wwyf** [comment]
看着是个奇怪的问题

**Comment by penglb3** [comment]
看上去和#26 是一样的问题？

**Comment by wangfh5** [comment]
> 看上去和#26 是一样的问题？

感谢

**Comment by Explorer-cc** [comment]
这一问题的原因可由 [muzimuzhi老师的解释](https://github.com/TheNetAdmin/zjuthesis/issues/53#issuecomment-609402095) 回答。

在《中山大学本科生毕业论文（设计）写作与印制规范》中指出：
> 标题一般用黑体，内容一般用宋体，数字和英文字母一般用Times New Roman

`Times New Roman`与`newtxtext`是有一些细微差异的，不过既然规范说的是“一般”，个人觉得：

https://github.com/SYSU-SCC/sysu-thesis/blob/7a1b7aaf0c48b197ddc8096094e0bb4ecd3bbdae/sysuthesis.cls#L35-L36

修改为：
```
% \setmainfont{Times New Roman} % 如果注释掉能正常编译，请注释
\RequirePackage{newtxtext} % 文本自动采用新罗马字体
```
似乎是一种比较简便的方法。当然，也可以根据`Times New Roman`对`\hbar`进行`\renewcommand`，调整一下相对高度，这样应该能做到除了`\hbar`，其他所有数字和英文字母都严格使用`Times New Roman`的字体。
