### ISSUE TITLE
引用格式问题

### ISSUE THREAD

**Issue by Sherlockids** [SYSU-SCC/sysu-thesis#42]
报错‘Illegal, another \bibstyle command’
查看.aux 文件，发现有两处定义 ‘\bibstyle{gbt7714-unsrt}’ 和 \bibstyle{gbt7714-numerical} 冲突，0.5版本更新中显示使用‘gbt7714-unsrt’但是下载的压缩包中没有该文件。

**Comment by Huangxt57** [comment]
尝试使用最新版本的 `xelatex` 进行编译？

**Comment by Huangxt57** [comment]
#24 见此，请使用 texlive 2020 或更新版本进行编译。
