### ISSUE TITLE
引用规范问题

### ISSUE THREAD

**Issue by VictoriousRaptor** [SYSU-SCC/sysu-thesis#44]
学校发布的论文规范要求为《信息与文献 参考文献著录规则》（GB/T 7714-2015），但项目中使用的是7714-2005？

**Comment by Huangxt57** [comment]
https://github.com/SYSU-SCC/sysu-thesis/blob/845ad9e01561ecb47c2dc54063cd0f934e58d1a7/sysuthesis.cls#L975，代码中使用的确实是 2015 版本，见 #24 。
