### ISSUE TITLE
overleaf参考文献显示不出来了 有参考文献四个字但内容全白

### ISSUE THREAD

**Issue by fuochai** [SYSU-SCC/sysu-thesis#49]
刚开始使用模板的时候好像注释掉某一句了 main.bib里没动 现在想改回来发现找不到那句话了 和原本的模板对比也找不到 究竟怎么回事
新建了一个模板把tex复制过去 一开始是没问题的 可过了一会儿参考文献又变成全白了！

**Comment by fuochai** [comment]
知道了 竟然要被引用过的才能在参考文献里显示

**Comment by HoyanMok** [comment]
可以用 
`\nocite{*}`
这个表示列出所有没有在文中被引用的参考文献
