### ISSUE TITLE
在main文件中添加宏包subfigure和图片路径命令\graphicspath后报错, 但是结果仍能输出

### ISSUE THREAD

**Issue by zhg6290** [SYSU-SCC/sysu-thesis#51]
1. subfigure宏包报错语句:
Command \c@lofdepth already defined. \newcounter{lofdepth}
2. \graphicspath命令报错语句:
File ended while scanning use of \@tempa. \graphicspath

**Comment by irenier** [comment]
`subfigure` 宏包与 `subcaption` 宏包冲突，只能使用其中一个。建议使用 `subcaption`。
