### ISSUE TITLE
PPT运行出错

### ISSUE THREAD

**Issue by lkp520** [SYSU-SCC/sysu-thesis#55]
Overfull \vbox (78.43489pt too high) detected at line 45
[17] [18]
Overfull \vbox (31.06857pt too high) detected at line 115
[19] [20] [21]
! Undefined control sequence.
<recently read> \cellcolor 
                           
l.258 }
       
?

**Comment by wu-kan** [comment]
见 #57 ，简化了 PPT 的代码。
