### ISSUE TITLE
ctex-fontset-adobe2.def 中的错误

### ISSUE THREAD

**Issue by ddddavid-he** [SYSU-SCC/sysu-thesis#61]
根据模板说明，如需使用自行下载的adobe字体需要使用`ctex-fontset-adobe2.def`文件定义字体，经过尝试发现该文件字体设置有缺陷，说明如下：

文件中通过此定义了\songti对应的字体：
```
\setCJKfamilyfont { zhsong } { AdobeSongStd-Light.otf }[
    Path = ./fonts/,
]
```
并在论文封面标题、章节标题使用  `\songti\textbf{<content>}` 指定格式，但是`\songti`对应的 `zhsong` 并未指定Bold样式，会导致加粗失败。

建议修改 `zhsong`定义与`\setCJKmainfont`相同，使之能正常进行加粗。即：

```
\setCJKmainfont  { AdobeSongStd-Light.otf }[
    Path=./fonts/,
    BoldFont   = AdobeHeitiStd-Regular.otf,
    ItalicFont = AdobeKaitiStd-Regular.otf
]
```

**Comment by Huangxt57** [comment]
Would you mind opening a PR?

**Comment by ddddavid-he** [comment]
Pull Request submitted
