### ISSUE TITLE
更新pre部分样式

### ISSUE THREAD

**Issue by Lovely-XPP** [SYSU-SCC/sysu-thesis#65]
主要调整如下：
1. 调整颜色为中大的标准色
2. 支持宽屏(16:9)输出
3. 引入个性化的定理、引理、假设、定义的环境
4. 更新参考文献的方式
5. 调整部分标题格式
6. 统一英文字体为Times New Roman

部分页面展示
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/66028151/213109734-fc4e5261-07a9-4d54-95a6-1a0e6a95dc10.png">

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/66028151/213109836-1619cb77-08bd-426e-bdf1-8b7bbbe3715f.png">

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/66028151/213109876-c7d5f341-e0b6-424e-9a52-0a5f908ec257.png">

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/66028151/213109939-335f6712-28de-48d1-8ce3-6b8921d13199.png">

整个文档可见 https://github.com/Lovely-XPP/sysu-thesis/blob/personality/presentation/pre.pdf

**Comment by Huangxt57** [comment]
Looks awesome🤩! Could you open a PR?

**Comment by Lovely-XPP** [comment]
No problem, I opened a PR just now.😁

**Comment by wu-kan** [comment]
见 #68 。
PPT 的样式涉及到不同人的需求，同时学校未对相对的格式做要求，目前这个仓库给出了一个最简单的 PRE 示例供大家进行学习和上手调整。我们欢迎大家自己定制一些符合自己要求的 SYSU-PRE 的仓库，然后我们在本仓库的 README 给出一个指向你的模板的链接作为推荐，但这个仓库的模板最好是"若无必要，勿增实体"（因为本仓库是学院推荐的论文模板，但 PRE 本身并没有学院站台）。

**Comment by Lovely-XPP** [comment]
好的，这里是我定制的模版，供大家参考：
https://github.com/Lovely-XPP/SYSU-PRE

**Comment by wu-kan** [comment]
> 好的，这里是我定制的模版，供大家参考： https://github.com/Lovely-XPP/SYSU-PRE

好，稍后我在 README 里面加一栏推荐一下。

**Comment by Lovely-XPP** [comment]
好的谢谢😁
