### ISSUE TITLE
mactex+texstudio 中文字符渲染全为空白

### ISSUE THREAD

**Issue by shilaoxiong** [SYSU-SCC/sysu-thesis#73]
环境：mactex+texstudio

已自行通过字体册导入fandol和adobe字体到mac系统中

渲染字体报错：
Font "FandolHei-Regular" does not contain requested(fontspec) Script "CJK".
（其他fandol字体同理，adobe字体没有报错）

渲染成功但中文全空白（间隔正确），英文正确。

**Comment by sikouhjw** [comment]
> 渲染字体报错： Font "FandolHei-Regular" does not contain requested(fontspec) Script "CJK". （其他fandol字体同理，adobe字体没有报错）

這不是 error，這是 warning。原因參考《[LaTeX 中文使用] 抑制 xeCJK/fontspec 警告 no-script "CJK"》[^1]

> 渲染成功但中文全空白（间隔正确），英文正确。

參考《一个texstudio的小问题：文字无法显示》[^2]

[^1]: https://zhuanlan.zhihu.com/p/145429470
[^2]: https://zhuanlan.zhihu.com/p/80728204

**Comment by shilaoxiong** [comment]
Issue resolved.

问题主因：内部pdf预览器无法渲然fandol字体。

解决办法：安装poppler。（更加详细的流程：https://blog.csdn.net/zhazhazl/article/details/124868148）
walkaround：参照Issue#29建议改用系统字体、或直接配置使用外部pdf预览器即可正常预览。
