### ISSUE TITLE
Proof里面没法使用\begin{equation}

### ISSUE THREAD

**Issue by river7816** [SYSU-SCC/sysu-thesis#74]

**Comment by sikouhjw** [comment]
这是基础知识，建议阅读 `TEXDOC LSHORT-ZH-CN` 入门。

问题在于，`equation` 环境不能有空行。

**Comment by river7816** [comment]
> 这是基础知识，建议阅读 `TEXDOC LSHORT-ZH-CN` 入门。
> 
> 问题在于，`equation` 环境不能有空行。

不好意思，我刚也发现了。有些草率，刚想来删您就回复了。
