### ISSUE TITLE
\autoref 在definition环境下显示错误

### ISSUE THREAD

**Issue by river7816** [SYSU-SCC/sysu-thesis#77]
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/114122443/227725406-36ce98d7-9889-4881-8d8a-6d239226d12d.png">
b并没有显示定义4.1,而是显示式4.1
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/114122443/227725455-81b9c235-8640-4ffa-9aee-3d1861b910aa.png">
请问如何修改才能将其改为式4.1

**Comment by note286** [comment]
你应该在`\begin{definition}`下一行写`\label`。

**Comment by river7816** [comment]
> 你应该在`\begin{definition}`下一行写`\label`。
您好，我尝试了，但是它提示`Package hyperref Warning: No autoref name for `definition' on input line 427.`
<img width="1820" alt="image" src="https://user-images.githubusercontent.com/114122443/227726613-a7b92d1b-07fb-41d9-879a-3139fd3f5256.png">
我需要在哪一个文件里自己定义吗？

**Comment by note286** [comment]
你参考一下 [hyperref - No autoref name for \`Appendix' - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/207744/no-autoref-name-for-appendix) ？我也没用过，这是我搜到的。

**Comment by river7816** [comment]
> 你参考一下 [hyperref - No autoref name for `Appendix' - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/207744/no-autoref-name-for-appendix) ？我也没用过，这是我搜到的。
感谢，已解决。在`sysuthesis.cls`文件1114行添加`\def\definitionautorefname{定义}%`即可解决
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/114122443/227727089-8d198154-91ed-4b4f-b276-04016fa2614f.png">
