### ISSUE TITLE
目录上方有大量空白

### ISSUE THREAD

**Issue by river7816** [SYSU-SCC/sysu-thesis#80]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/114122443/232499514-83a4fef1-9777-4f99-b899-55c20a6bde8b.png">
目录上方有大量空白导致又多出一页，请问如何调整

**Comment by 1FCENdoge** [comment]
这个好像是ctexbook的设定，这两个字它就会放在这里，多的一页就让它多吧……正文第一页要从奇数页面开始的话就加个\cleardoublepage命令

**Comment by 1FCENdoge** [comment]
详见.cls文件的第888-891行，此处可调节距离
![image](https://github.com/SYSU-SCC/sysu-thesis/assets/86185801/28dfb71a-a959-4dd0-aa4f-e7d0a3083803)

**Comment by river7816** [comment]
> 详见.cls文件的第888-891行，此处可调节距离 ![image](https://private-user-images.githubusercontent.com/86185801/292619173-28dfb71a-a959-4dd0-aa4f-e7d0a3083803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzUzODAsIm5iZiI6MTcwMzMzNTA4MCwicGF0aCI6Ii84NjE4NTgwMS8yOTI2MTkxNzMtMjhkZmI3MWEtYTk1OS00ZGQwLWFhNGYtZTdkMGEzMDgzODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEyMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlN2M3NGJhMDBlMWQzNjk3YjMxZDRkNGUyOTIwN2FjNjNhYTY3NTA1MmI5YzdmOTJkN2NiYTAzNzk4NmQxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8gfO3LYSNOWGly-j7z3_SfTWlZ0dBySPvuAGgDmOXJ8)

谢谢回复，但是我已经毕业啦

**Comment by 1FCENdoge** [comment]
> > 详见.cls文件的第888-891行，此处可调节距离 ![image](https://private-user-images.githubusercontent.com/86185801/292619173-28dfb71a-a959-4dd0-aa4f-e7d0a3083803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzUzODAsIm5iZiI6MTcwMzMzNTA4MCwicGF0aCI6Ii84NjE4NTgwMS8yOTI2MTkxNzMtMjhkZmI3MWEtYTk1OS00ZGQwLWFhNGYtZTdkMGEzMDgzODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEyMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlN2M3NGJhMDBlMWQzNjk3YjMxZDRkNGUyOTIwN2FjNjNhYTY3NTA1MmI5YzdmOTJkN2NiYTAzNzk4NmQxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8gfO3LYSNOWGly-j7z3_SfTWlZ0dBySPvuAGgDmOXJ8)
> 
> 谢谢回复，但是我已经毕业啦

T^T
