### ISSUE TITLE
目录显示与章节编号

### ISSUE THREAD

**Issue by Rui-Alexander-Sun** [SYSU-SCC/sysu-thesis#82]
有时我们希望某些章节（例如摘要或结语）不编号，但又显示在目录当中，可以在相关位置：
`\chapter*{结语}`
`\addcontentsline{toc}{chapter}{结语}`

其中第一行 * 的作用是不编号，第二行的作用是把这一章节添加进目录中，所以如果希望既不编号也不添加进目录，可以删去第二行

参考自：
https://zhuanlan.zhihu.com/p/24501131

**Comment by Rui-Alexander-Sun** [comment]
上面的代码忘记换行了，改为：
`\chapter*{结语}`
`\chapter*{结语} \addcontentsline{toc}{chapter}{结语}`

**Comment by wu-kan** [comment]
感谢，不过这类tips可以发在 [discussions](https://github.com/SYSU-SCC/sysu-thesis/discussions) 里面，免得close了issue之后大伙看不到😄

**Comment by Rui-Alexander-Sun** [comment]
> 感谢，不过这类tips可以发在 [discussions](https://github.com/SYSU-SCC/sysu-thesis/discussions) 里面，免得close了issue之后大伙看不到😄

好滴，因为我对Github不是很熟，所以就发在了这里哈哈。我去发在discussion~
