### ISSUE TITLE
请问这个模板如何添加宏包和自定义命令？

### ISSUE THREAD

**Issue by CaviarSP** [SYSU-SCC/sysu-thesis#89]
如题，请问这个模板如何添加宏包和自定义命令？感谢回复。

**Comment by 1FCENdoge** [comment]
这个问题不妨问得更清楚一些，比如你想添加哪个宏包，实现什么样的功能？
如果添加宏包的话，一般直接修改.cls文件，那些\RequirePackage命令后面的内容都是宏包。

**Comment by CaviarSP** [comment]
感谢回复。
我想要画数独，为了方便要用到自定义命令
`\newcommand\setrow[9]{
        \setcounter{col}{1}
        \foreach \n in {#1, #2, #3, #4, #5, #6, #7, #8, #9} {
            \edef\x{\value{col} - 0.5}
            \edef\y{9.5 - \value{row}}
            \node[digit,name={\arabic{row}-\arabic{col}}] at (\x, \y) {\n};
            \stepcounter{col}
        }
        \stepcounter{row}
    }`
出于排版需求要用到subfig宏包。

我刚刚尝试了在sysuthesis.cls 中添加\RequirePackage{subfig}，然后编译时main.tex的\begin{document}行报错。

**Comment by CaviarSP** [comment]
> 这个问题不妨问得更清楚一些，比如你想添加哪个宏包，实现什么样的功能？ 如果添加宏包的话，一般直接修改.cls文件，那些\RequirePackage命令后面的内容都是宏包。

感谢回复。
我想要画数独，为了方便要用到自定义命令
`\newcommand\setrow[9]{
        \setcounter{col}{1}
        \foreach \n in {#1, #2, #3, #4, #5, #6, #7, #8, #9} {
            \edef\x{\value{col} - 0.5}
            \edef\y{9.5 - \value{row}}
            \node[digit,name={\arabic{row}-\arabic{col}}] at (\x, \y) {\n};
            \stepcounter{col}
        }
        \stepcounter{row}
    }`
出于排版需求要用到subfig宏包。

我刚刚尝试了在sysuthesis.cls 中添加\RequirePackage{subfig}，然后编译时main.tex的\begin{document}行报错。

**Comment by 1FCENdoge** [comment]
> > 这个问题不妨问得更清楚一些，比如你想添加哪个宏包，实现什么样的功能？ 如果添加宏包的话，一般直接修改.cls文件，那些\RequirePackage命令后面的内容都是宏包。
> 
> 感谢回复。 我想要画数独，为了方便要用到自定义命令 `\newcommand\setrow[9]{ \setcounter{col}{1} \foreach \n in {#1, #2, #3, #4, #5, #6, #7, #8, #9} { \edef\x{\value{col} - 0.5} \edef\y{9.5 - \value{row}} \node[digit,name={\arabic{row}-\arabic{col}}] at (\x, \y) {\n}; \stepcounter{col} } \stepcounter{row} }` 出于排版需求要用到subfig宏包。
> 
> 我刚刚尝试了在sysuthesis.cls 中添加\RequirePackage{subfig}，然后编译时main.tex的\begin{document}行报错。

自定义命令还是在.cls文件中添加，添加subfig宏包出错可以检查一下代码中是否包含subfigure命令，包括正文章节的代码中，subfig和subfigure两个命令是冲突的。参考[此处](https://blog.csdn.net/yzy_1996/article/details/117574086)

**Comment by CaviarSP** [comment]
> > > 这个问题不妨问得更清楚一些，比如你想添加哪个宏包，实现什么样的功能？ 如果添加宏包的话，一般直接修改.cls文件，那些\RequirePackage命令后面的内容都是宏包。
> > 
> > 
> > 感谢回复。 我想要画数独，为了方便要用到自定义命令 `\newcommand\setrow[9]{ \setcounter{col}{1} \foreach \n in {#1, #2, #3, #4, #5, #6, #7, #8, #9} { \edef\x{\value{col} - 0.5} \edef\y{9.5 - \value{row}} \node[digit,name={\arabic{row}-\arabic{col}}] at (\x, \y) {\n}; \stepcounter{col} } \stepcounter{row} }` 出于排版需求要用到subfig宏包。
> > 我刚刚尝试了在sysuthesis.cls 中添加\RequirePackage{subfig}，然后编译时main.tex的\begin{document}行报错。
> 
> 自定义命令还是在.cls文件中添加，添加subfig宏包出错可以检查一下代码中是否包含subfigure命令，包括正文章节的代码中，subfig和subfigure两个命令是冲突的。参考[此处](https://blog.csdn.net/yzy_1996/article/details/117574086)

按你说的解决了。十分感谢| ᐕ)⁾⁾。
