### ISSUE TITLE
MikTex 兼容问题

### ISSUE THREAD

**Issue by MMMMMoris** [SYSU-SCC/sysu-thesis#93]
最近刚开始用 LaTeX
TexLive 好像有些 bug 还是啥，Windows 11 装不上，无法更改安装位置
索性放弃 TexLive，使用 MikTex 顺利安装
但是模板提示用 TexLive 编译，我在 VSCode 编译的时候也遇到不少报错，由于是新手，不是很看得懂报错内容
![image](https://github.com/SYSU-SCC/sysu-thesis/assets/63332824/d2e191b5-ad46-4bdf-a43b-16c7a6d09314)
我怀疑是不是 MikTex 不兼容的问题
以及，文档里面提到的 `Make pdf` 命令，似乎 MikTex 也没有这个命令，无法直接在终端调用 `Make pdf`

## 所以来请教下，本模板是否兼容 MikTex

**Comment by sikouhjw** [comment]
1. 兼容。
2. 这是警告，不是报错。这些警告是模板没设置好导致的，不需要理会，除非影响使用。

**Comment by MMMMMoris** [comment]
> 1. 兼容。
> 2. 这是警告，不是报错。这些警告是模板没设置好导致的，不需要理会，除非影响使用。

好的，谢谢
那请问一下 关于 `Make pdf` 这个命令是 Linux 专属的吗？我在 Windows 上只有 cmake 这个 make 工具，还是专门用于 C 程序编译的。用于 C 编译的 `make` 和彼 `Make pdf` 是一样的吗？

**Comment by MMMMMoris** [comment]
使用 msys2 的 make 工具成功解决问题，多谢

> > 1. 兼容。
> > 2. 这是警告，不是报错。这些警告是模板没设置好导致的，不需要理会，除非影响使用。
> 
> 好的，谢谢 那请问一下 关于 `Make pdf` 这个命令是 Linux 专属的吗？我在 Windows 上只有 cmake 这个 make 工具，还是专门用于 C 程序编译的。用于 C 编译的 `make` 和彼 `Make pdf` 是一样的吗？
